### ISSUE TITLE
[drone_teleop] Cameras and pos/vel freeze in new GUI

### ISSUE THREAD

**Issue by diegomrt** [JdeRobot/drones#38]
Each 20/30 sec both the cameras and the position/velocities freeze in the new drone_teleop GUI, as it's seen in the screenshot below. Tested using the new drone_teleop_all.perspective. 

Clicking in some precise points/controls of the GUI unfreeze the perspective temporarily.

![Captura de pantalla de 2020-05-29 18-37-03](https://user-images.githubusercontent.com/35877889/83284918-b2ede180-a1dd-11ea-964d-1d9d0268af9f.png)

**Comment by diegomrt** [comment]
I think we should try if [throttling](http://wiki.ros.org/topic_tools/throttle) the mavros pose and vel topics to rates < 5 Hz (now they publish at 30 Hz) avoids this issue. 

I've checked the cameras perspective alone and it doesn't freeze.

**Comment by pariaspe** [comment]
The problem seems to be that the GUI can not update itself as fast as the Subscribers receive msgs with the pose and twist. Then, as you suggest, msgs have to be throttled to reduce the GUI update rate.

This bug could be fixed by creating a Thread which periodically updates the position and velocity info:
```python
threading.Timer(0.5, self.update_status_info).start()
```

I've tried more ROS friendly solutions using [rospy.Timer](http://docs.ros.org/jade/api/rospy/html/rospy.timer.Timer-class.html), [throttle](http://wiki.ros.org/topic_tools/throttle) or [drop](https://wiki.ros.org/topic_tools/drop), but I didn't get any working solution.

**Comment by diegomrt** [comment]
Hi @pariaspe, I seems good to me if it works and it doens't overload the CPU. 

In any case, ROS-based solutions could rely on suscribing the GUI to new throttled pose and vel topics, that can be published at least in two different ways:

- Launching a ROS throttling node directly from the exercise .launch (easiest way, a line of code)
- Building our own "republish 1, discard the next 14 messages" solution within the drone_wrapper, which is capable of handling easily the actual 30 Hz callbacks

**Comment by pariaspe** [comment]
I've just created a new issue to implement a new ROS-based solution that fixes this issue too.
